/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    copy: typeof import('./src/components/page/Board/Notice/NoticeSearch copy.vue')['default']
    FirstNoticeMain: typeof import('./src/components/page/Board/Notice/FirstNoticeMain.vue')['default']
    FirstNoticeModal: typeof import('./src/components/page/Board/Notice/FirstNoticeModal.vue')['default']
    FirstNoticeSearch: typeof import('./src/components/page/Board/Notice/FirstNoticeSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    NoticeDetail: typeof import('./src/components/page/Board/Notice/NoticeDetail.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeModal: typeof import('./src/components/page/Board/Notice/NoticeModal.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
